### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by tpetr**

### CODE REVIEW

**Comment by cce** [comment]
Thanks! Unfortunately some kind of Travis/Coveralls integration problem broke the build, hrmm:
image

**Comment by cce** [comment]
Oh I see, Travis is not putting `$COVERALLS_TOKEN` into the build environment when it runs goveralls.
image

**Comment by cce** [comment]
That is strange because it remains set in the Travis build settings.

**Comment by tpetr** [comment]
Weird, thanks for looking into it. Could it be related to the fact that the PR is originating from the `tpetr` fork?

**Comment by cce** [comment]
Hopefully Travis will fix the issue! Thanks, merging!

**Comment by tpetr** [comment]
🙏

**Comment by cce** [comment]
Oh perhaps secret env vars like that aren't available for builds of forked PRs, hrmm hadn't thought of that! That would make it harder to test PRs for coverage though.

**Comment by cce** [comment]
You're right: "we do not provide these values to untrusted builds, triggered by pull requests from another repository." https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by cce** [comment]
Also, the semaphore build link for this PR leads to a 404. Mysterious!

**Comment by tpetr** [comment]
Indeed. It could be because I deleted the branch after the merge, though restoring it didn't seem to have helped. 😞

**Comment by cce** [comment]
no worries! we'll figure it out when you submit your next PR with new code & tests.

**Pull request merged**
